# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e0e5babdeb581cf78cf8db35f1657b1180c69904ed316c4d2dea0756cac443858b22934d37be6250e5880e5f3c7b8fc13cf0a7acc01cb13b5b66eef3729aefc

test:
  secret_key_base: 387faf82be7a877ae8b762022068f6ca06e599236296600cc331624ec21cfff7fb324a384686189152c90ade5d6f5c890d058f778987a4eff98a7ded68fd87d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
